const mongoose = require('mongoose');
var ObraSocial = mongoose.model('ObraSocial');

const Schema = mongoose.Schema

const PacienteSchema = new Schema({
    Personal: {
        Nombre: String,
        Apellido: String,
        ObraSocial: { type: Schema.ObjectId, ref: "ObraSocial" },
        NºAfil:  Number,
        FechaNac: Date,
        Edad: Number,
        Documento: Number,
        Telefono: Number,
        Email: String,
        Domicilio: String,
        EstadoCivil: String,
        FechaAlta: {
            type: Date,
            default: Date.now
        }
    },
    HistoriaClinica: {
        MedicoCabecera: String,
        ServUrgenciaBool: { type: Boolean, default: false},
        ServUrgen: String,
        HospitalizacionBool: { type: Boolean, default: false},
        HospitalizacionRazon: String,
        TratamientoMedicoBool: { type: Boolean, default: false},
        TratamientoMedicoRazon: String,
        Alergias: [String],
        Afecciones: { 
                "Problemas cardiacos": { type: Boolean, default: false}, 
                "Presion sanguinea alta": { type: Boolean, default: false},
                "Presion sanguinea baja": { type: Boolean, default: false},
                "Enfermedades venereas": { type: Boolean, default: false},
                "Fiebre Reumatuca": { type: Boolean, default: false},
                "Hepatitis": { type: Boolean, default: false},
                "Ulcera de estomago": { type: Boolean, default: false}, 
                "Dolor de cabeza": { type: Boolean, default: false}, 
                "Sida": { type: Boolean, default: false}, 
                "Epilepsia": { type: Boolean, default: false}, 
                "Artitris": { type: Boolean, default: false}, 
                "Cancer": { type: Boolean, default: false}, 
                "Diabetes": { type: Boolean, default: false}, 
                "Aleteraciones Nerviosas": { type: Boolean, default: false}, 
                "Sinusitis": { type: Boolean, default: false}, 
                "Otras": { type: Boolean, default: false}           
        },
        Medicamentos: [String],
        FumaBool: { type: Boolean, default: false},
        FumaCuanto: Number,
        BebeBool: { type: Boolean, default: false},
        BebeCuanto: Number,
        EmbarazadaBool:  { type: Boolean, default: false},
        EmbarazadaTiempo: Number,
        ProblemaRadiante: { type: Boolean, default: false},
        Otros: String,
        Observaciones: String,
        DificultadHablar: { type: Boolean, default: false},
        DificultadMasticar: { type: Boolean, default: false},
        DificultadAbrirBoca: { type: Boolean, default: false},
        MovilidadEnDientes: { type: Boolean, default: false},
        EnciasSangrantes: { type: Boolean, default: false},
        PusBoca: { type: Boolean, default: false},
        PusDonde: String,
        EstadoHigieneBucal: String,
        EstadoDeTejidosBlandos: {
            Lengua: String,
            Carillos: String,
            PresentaSarro: { type: Boolean, default: false},
            Labios: String,
            PisoDeBoca: String,
            EstadoGfngivoPeropdontal: String,
            CantidadDientes: String,
            EnfermedadPeriodental: String
        }   
    },
    Odontograma: {
        Pieza11: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza12: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza13: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ], 
        Pieza14: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza15: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza16: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza17: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza18: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza21: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza22: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza23: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza24: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza25: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza26: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza27: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza28: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza31: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza32: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza33: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza34: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza35: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza36: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza37: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza38: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza41: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza42: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza43: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza44: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza45: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza46: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza47: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ],
        Pieza48: [ { Fecha: Date, Caras: [String], Estado: String, Tratamiento: { type: Schema.ObjectId, ref: "Tratamiento" } } ]
    },
})

module.exports = mongoose.model('Paciente', PacienteSchema)